### PR TITLE
Feature/login signup prompt

### PR DESCRIPTION
**Pull request by sFranchetto**
Closes 
https://github.com/awaazo/awaazo/issues/377
&
 https://github.com/awaazo/awaazo/issues/369

### CODE REVIEW

**Review by jonathan-githubofficial — CHANGES_REQUESTED** [review]
Nice work 👍. Here are some things that should be changed to improve our lives later on:

1. Instead of duplicating the login code in both `LoginPrompt` and `LoginPage`, create a single component `component/auth/Login.tsx` and import it where you need it. This removes the need to test different components with Cypress and redundancy in the code overall.

2. Rather than repeating login checks and redirection logic in each component, implement a higher-order component for authentication `utilities/authHOC.tsx` and wrap this around pages or components that can't be accessed unless the user is logged in. This makes the code cleaner and more manageable with high cohesion.

**Comment by jonathan-githubofficial** [comment]
> Nice work 👍. Here are some things that should be changed to improve our lives later on:
> 
> 1. Instead of duplicating the login code in both `LoginPrompt` and `LoginPage`, create a single component `component/auth/Login.tsx` and import it where you need it. This removes the need to test different components with Cypress and redundancy in the code overall.
> 2. Rather than repeating login checks and redirection logic in each component, implement a higher-order component for authentication `utilities/authHOC.tsx` and wrap this around pages or components that can't be accessed unless the user is logged in. This makes the code cleaner and more manageable with high cohesion.

authHoc was added . import it to the pages of the components you need like so , for example:

`import withAuth from "utilities/authHOC.tsx"`
`const MyProfile = () => {
  // bla bla bla 
};`
`export default withAuth(MyProfile); `

**Comment by sFranchetto** [comment]
Instead of duplicating the login code in both LoginPrompt and LoginPage, create a single component component/auth/Login.tsx and import it where you need it. This removes the need to test different components with Cypress and redundancy in the code overall.

Addressed in: https://github.com/awaazo/awaazo/pull/378/commits/46ee1105308afc7e2c0b009bda8c55c2974c828d

**Comment by sFranchetto** [comment]
"Rather than repeating login checks and redirection logic in each component, implement a higher-order component for authentication utilities/authHOC.tsx and wrap this around pages or components that can't be accessed unless the user is logged in. This makes the code cleaner and more manageable with high cohesion."

Addressed in https://github.com/awaazo/awaazo/pull/378/commits/d2c9a81ccb23882f6995be0aa9f84c84dd329e6a

**Review by jonathan-githubofficial — CHANGES_REQUESTED** [review]
comments are still accessible even if the user is not logged in .

**Comment by jonathan-githubofficial** [comment]
> comments are still accessible even if the user is not logged in .

A user can see comments but can't comment/reply .
this approach is fine for this stage of the comments' component development.

**Review by jonathan-githubofficial — APPROVED** [review]

**Review by AwaazoOfficial — APPROVED** [review]

**Pull request merged**
