### PR TITLE
Issue #103/sensitive information exposed in envlocal file

### LINKED ISSUE #103: Sensitive Information Exposed in .env.local File
There appears to be sensitive information, NEXT_PUBLIC_BASE_URL, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, and NEXTAUTH_URL, stored in the .env.local file. They must moved to GitHub secrets to uphold security.

### PR DESCRIPTION
**Pull request by mathieutrudeau**
This Pull Request involves 15 changes, all of which are additions with no deletions. The changes primarily focus on the .github/workflows/frontend.yml and .gitignore files.

In the .github/workflows/frontend.yml file:

A set of environment variables (GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, BASE_URL, and NEXT_AUTH_URL) have been added.
A new file named .env.local has been created within the "frontend" directory.
The values of the environment variables have been populated in the .env.local file.
An additional step for installing dependencies has been incorporated into the workflow.
In the .gitignore file:

A new pattern, *.env.local, has been introduced to exclude files with this specific extension from version control.
These changes are geared towards enhancing the project's configuration, managing environment variables, and ensuring that specific configuration files are not tracked by Git.

closes #103

### CODE REVIEW

**Review by sFranchetto — APPROVED** [review]
Good call abstracting the sensitive information. Doing these changes on the fly are crucial for maintaining a robust and secure development environment.

However, it's imperative to thoroughly verify that the abstraction process has been executed effectively and that the sensitive information remains secure and inaccessible throughout the development lifecycle. This includes conducting rigorous testing to confirm that the changes do not inadvertently expose any sensitive data and that the overall functionality of the project remains unaffected.

If these changes don't cause conflicts and the abstraction is properly functioning then merge branch & delete.

**Review by BigSaladMan — CHANGES_REQUESTED** [review]
You missed some. There are some exposed ones in the appsettings.Development.json and the appsettings.json in the Backend Folder

**Comment by BigSaladMan** [comment]
There is also some in the backend.tests folder

**Comment by mathieutrudeau** [comment]
> You missed some. There are some exposed ones in the appsettings.Development.json and the appsettings.json in the Backend Folder

**Comment by mathieutrudeau** [comment]
@BigSaladMan Added the requested changes

**Review by BigSaladMan — APPROVED** [review]

**Pull request merged**
