### PR TITLE
Added reset password page

### PR DESCRIPTION
**Pull request by Ahed752**
Closes : #374 
- Added Forgot Password Functionality allowing users to request a password reset link if they've forgotten their password. 
- Created Reset Password Component to set a new password via the link sent to their email. 
- Enhanced Email Handling includes validation checks to ensure that reset links are sent to registered emails only and handling edge

### CODE REVIEW

**Review by jonathan-githubofficial — CHANGES_REQUESTED** [review]
no need to create a separate page for reset password. you can import the component to auth/[...authPage].tsx instead.

**Comment by Ahed752** [comment]
> no need to create a separate page for reset password. you can import the component to auth/[...authPage].tsx instead.

done,thanks!

**Review by soni2261 — APPROVED** [review]
would be great to change/add the colors/variants to frontend>styles>AppTheme.tsx to reduce redundancy. the rest looks good though, great work!

**Review by jonathan-githubofficial — APPROVED** [review]

**Review by sFranchetto — APPROVED** [review]
Looks good! Nice work :)

**Pull request merged**
