### PR TITLE
Added CRUD API routes for user bookmarks

### PR DESCRIPTION
**Pull request by shadijiha**
This PR closes issue : #184

### CODE REVIEW

**Comment by usamasaleem1** [comment]
small merge conflict

**Review by mathieutrudeau — APPROVED** [review]
Looks good. Make sure to solve the conflicts before merging.

**Comment by jonathan-githubofficial** [comment]
fixed the merge conflict  

> small merge conflict

merge conflict was fixed.

**Review by jonathan-githubofficial — APPROVED** [review]
Looks good .

**Pull request merged**
