### PR TITLE
Dev/transcript generation

### PR DESCRIPTION
**Pull request by mathieutrudeau**
## Additions:

- **Python Server for Interactions:**
  - Introduction of a robust Python server to handle interactions for current and future scripts.

- **Speech-to-Text Script (stt.py):**
  - Development of stt.py, a Python script using OpenAI's Whisper for accurate audio-to-text transcription.

- **Docker Image for Python Server:**
  - Creation of a Dockerfile for the new Python server, simplifying deployment and ensuring consistency.

- **Docker Compose Integration:**
  - Integration of the Python server as a service in the Docker Compose file for easy management and deployment.

- **Optimized for CUDA-Enabled Nvidia GPU:**
  - Transcription service operates considerably faster with CUDA-enabled Nvidia GPUs.
  - CPU handling available for setups without this hardware, ensuring functionality.

### CODE REVIEW

**Comment by mathieutrudeau** [comment]
The docker-compose on the CI will fail because the python folder is not on main yet. This will cause the E2E tests to fail.

**Comment by mathieutrudeau** [comment]
The E2E tests do, however, pass on my machine while running against the containers brought up by the docker-compose file.
Capture

**Review by Radwanbaba13 — APPROVED** [review]
Nice job on the transcript generator, the format it gives is ideal for what we're doing, looking forward to use it on the frontend

**Review by jonathan-githubofficial — APPROVED** [review]
looks good 👍

**Pull request merged**
