### PR TITLE
Fix fetch podcasts episodes

### LINKED ISSUE #240: MyProfile - Social Links and Subscription Issues
### Description:

- [ ] Social links don't appear when creating a user, but do when editing.
- [ ] Hardcoded subscription and podcast subscriptions.
- [ ] Icon order is reversed compared to the edit page.
- [ ] Links can redirect to unsafe URLs.
- [ ] profile/Setup redirects to a null entity when already logged in.

### PR DESCRIPTION
**Pull request by Ahed752**
This Pull request addresses the following issues:
- added share Playlist component to allow users share their favorites on other social media platforms.
-  removed annotations from the NowPlaying and added in its correct place for each episode.
- added asynchronous functions to fetch episodes, playlists and podcasts.
- added loading spinners to display fetch requests in progress.
- removed the hardcoded subscription logic
- removed some links that redirected to unsafe URLs

closes #240 #300 #311

### CODE REVIEW

**Review by jonathan-githubofficial — CHANGES_REQUESTED** [review]
Make sure the way we add annotations is similar to how we add sections. Use modules and the 'SectionsPlayingBar'  component as a reference for choosing timestamps. Also, move the components related to annotations from the 'nowPlaying' folder to a different folder

**Comment by Ahed752** [comment]
> Make sure the way we add annotations is similar to how we add sections. Use modules and the 'SectionsPlayingBar' component as a reference for choosing timestamps. Also, move the components related to annotations from the 'nowPlaying' folder to a different folder

I made the requested changes, lmk if that's what you mean

**Comment by jonathan-githubofficial** [comment]
> > Make sure the way we add annotations is similar to how we add sections. Use modules and the 'SectionsPlayingBar' component as a reference for choosing timestamps. Also, move the components related to annotations from the 'nowPlaying' folder to a different folder
> 
> I made the requested changes, lmk if that's what you mean


- time stamps should not be an open text input form field .
- time stamps length should be limited to the length of the episode 
- there's no error handling for out of range values .

**Review by jonathan-githubofficial — APPROVED** [review]

**Review by sFranchetto — APPROVED** [review]
Looks great! Nice Job :)

**Pull request merged**
